function  Properties_Of_Matrices()
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
disp('                  WELCOME TO PROPERTIES OF MATRICES');
disp('                  *********************************');
disp(' ');
disp('What is matrix?');
disp('===============')
disp('         "A matrix is a rectangular array of numbers,symbols or ');
disp('          expressions arranged in rows and columns."');
disp(' Elements:');
disp(' =========');
disp('         "The individual items in a matrix are called its elements');
disp('          or entries."');
disp(' Example:');
disp(' ========');
M1=round(100*rand(3:3));
disp(M1);
disp('Types of Matrices:');
disp('==================');
disp('                1-Row Matrics');
disp('                2-Column Matrics');
disp('                3-Square Matrics');
disp('                4-Rectangular Matrics');
disp('                5-Triangular Matrics');
disp('                6-Diagonal Matrics');
disp('                7-Identity Matrics');
disp('                8-Zero Matrics');
disp('                9-Scalar Matrics');
disp('                10-Transpose Matrics');
disp('                11-Regular Matrics');
disp('                12-Singular Matrics');
disp('                13-Non-Singular Matrics');
disp('                14-Idempotent Matrics');
disp('                15-Involutive Matrics');
disp('                16-Symmetric Matrics');
disp('                17-Anti-Symmetric Matrics');
disp('                18-Orthogonal Matrics');
disp('1- Row Matrix:');
disp(' =============');
disp('		  A matrix with a single row is called Row Matrix.');
disp('		  e.g.');
disp(' ');
M2=round(100*rand(1,3));
disp(M2);
disp('2-Column Matrix:');
disp(' ===============');
disp('		  A matrix with a single column is called Column Matrix.');
disp('		  e.g.');
disp(' ');
M3=round(100*rand(3,1));
disp(M3);
disp('3-Square Matrix:');
disp(' ===============');
disp('		 A matrix with the same number of rows and columns is called');
disp('         Square Matrix.');
disp('		     e.g.');
disp(' ');
M4=round(100*rand(2,2));
disp(M4);
disp('4-Rectangualr Matrix:');
disp(' ====================');
disp('		    A matrix with the different number of rows and columns is ');
disp('            called Rectangualr Matrix.');
disp('		    e.g.');
disp(' '); 
M5=round(100*rand(3,2));
disp(M5);
disp('5-Triangular matrix:');
disp(' ===================');
disp('		    There are two different types of Triangular matrix.');
disp('		    i. Upper Triangular Matrix');
disp('             ==========================');
disp('				        In an upper triangular matrix, the elements ');
disp('                        located below the diagonal are zeros.');
disp('				        e.g.');
disp(' '); 
disp('                       2  1  9');
disp('                       0  2  8');
disp('                       0  0  7');
disp('		    ii.Lower Triangular Matrix');
disp('             ==========================');
disp('				            In a lower triangular matrix, the elements ');
disp('                            above the diagonal are zeros.');
disp('				            e.g.');
disp('                       2  0  0');
disp('                       3  2  0');
disp('                       5  1  7');
disp('6-Diagonal Matrix:');
disp(' =================');
disp('		    In a diagonal matrix, all the elements above and below the ');
disp('            diagonal are zeros.');
disp('		       e.g.');
disp(' ');
disp('            2  0  0');
disp('            0  6  0');
disp('            0  0  8');
%M5=round(round(100*rand(4:4)));
%A=diag(M5);
%disp(A);
disp('7-Identity Matrix:');
disp(' =================');
disp('		    An identity matrix is a diagonal matrix in which the diagonal');
disp('            elements are equal to 1.');	
disp('		    e.g.');
disp(' ');
disp('            1  0  0');
disp('            0  1  0');
disp('            0  0  1');
disp('8-Zero matrix:');
disp(' =============');
disp('		     In a zero matrix, all the elements are zeros.');
disp('		     e.g.');
disp(' ');
M6=round(0*rand(3:3));
disp(M6);
disp('9-Scalar matrix:');
disp(' ===============');
disp('		     A scalar matrix is a diagonal matrix in which the diagonal ');
disp('             elements are equal.');
disp('		     e.g.');
disp(' ');
disp('      2  0  0');
disp('      0  2  0');
disp('      0  0  2');
disp('10-Transpose Matrix:');
disp(' ===================');
disp('           Given matrix A, the transpose of matrix A is another ');
disp('           matrix where the elements in the columns and rows ');
disp('           have switched.In other words,the rows becomes the ');
disp('           columns and the columns become the rows.	   ');
disp('           e.g.');
disp(' ');
M1=round(100*rand(3:3));
disp(M1);
disp('    Now the transpose of this matrix will be as follows:');
b=transpose(M1);
disp(b);
disp('11-Regular Matrix:');
disp(' =================');
disp('           A regular matrix is a square matrix that has an inverse.');
disp('           e.g.');
disp(' ');
disp('            1  2');
disp('            0  2');
disp('           Note ::');
disp('           To learn,how to find the inverse of a matrix,switch to ');
disp('           option FIND INVERSE.');
disp('12-Singular Matrix:');
disp(' ==================');
disp('           A singular matrix is a square matrix that has no inverse.');
disp('           e.g.');
disp(' ');
disp('            0  0');
disp('            0  0');
disp('13-Non-Singular Matrix:');
disp(' ======================');
disp('           A non-singular matrix is a matrix whixh has determinant ');
disp('           non-zero.');
disp('           e.g.');
disp(' ');
disp('            1  2');
disp('            2  0');
disp('14-Idempotent Matrix:');
disp(' ====================');
disp('            The matrix A is idempotent if:');
disp('            A2=A');
disp('            e.g.');
disp(' ');
disp('            -1   0');
disp('             0  -1');
disp('15-Involutive Matrix:');
disp(' ====================');
disp('            The matrix A is involutive if:');
disp('            A2=I');
disp('            e.g.');
disp(' ');
disp('            1   0');
disp('            0  -1');
disp('16-Symmetric Matrix:');
disp(' ===================');
disp('            A symmetric matrix is a square matrix that verifies:');
disp('            A=At');
disp('            e.g.');
disp(' ');
disp('            1  0');
disp('            0  2');
disp('17-Anti-Symmetric Matrix:');
disp(' ========================');
disp('            An antisymmetric matrix is a square matrix that verifies:');
disp('            A=-At');
disp('            e.g.');
disp(' ');
disp('            0  -3  -4');
disp('            3   0  -9');
disp('            4   9   0');
disp('18-Orthognal Matrix:');
disp(' ===================');
disp('            A matrix is orthogonal if it verifies that:'); 
disp('            A·At = I');
disp('            e.g.');
disp(' ');
disp('PROPERTIES OF MATRICES:');
disp('=======================');
disp('       1-Properties involving Addition:');
disp('       ==================================');
disp('            Let A, B, and C be mxn matrices. We have, ');
disp(' ');
disp('                   1.A+B = B+A ');
disp(' ');
disp('                   2.(A+B)+C = A + (B+C)');
disp(' ');
disp('                   3.A+0=A');
disp('                          where A is the mxn zero-matrix (all its');
disp('                          entries are equal to 0) ');
disp(' ');
disp('                   4.A+B=0');
disp('                           if and only if B = -A ');
disp(' ');
disp('        2-Properties involving Multiplication: ');
disp('        =======================================');
disp(' ');
disp('                   1.Not commutative: ');
disp('                       In general: ');
disp('                             AB!=BA');
disp(' ');
disp('                   2.Let A, B, and C be three matrices. If you can');
disp('                   perform the products AB, (AB)C, BC, and A(BC), ');
disp('                   then we have ');
disp('                              (AB)C = A(BC) ');
disp(' ');
disp(' ');
disp('                    Note::');
disp('                        For example,that if A is 2x3, B is 3x3,and');
disp('                        C is 3x1, then the above products are ');
disp('                        possible(in this case,(AB)C is 2x1 matrix)');
disp(' ');
disp('                    3.If a and b are numbers, and A is a matrix, ');
disp('                    then we have ');
disp('                              a(bA)=(ab)A ');
disp(' ');
disp('                    4.If a is a number,and A and B are two matrices');
disp('                    such that the product is possible,then we have');
disp('                              a(AB)=(aA)B=A(aB)');
disp(' ');
disp('                    5.If A is nxm matrix and the mxk zero-matrix,');
disp('                    then  ');
disp('                              A0=0');
disp(' ');
%disp('OPERATIONS OF MATRICES:');
%disp('=======================');
%disp('                  Here are some operations which we can perform on');
%disp('                  Matrices.');
%disp('1-Matrix Dimensions:');
%disp('=====================');
%disp('                  Dimensions of matrix can be find  by analyzing ');
%disp('                  rows and columns of that matrix.');
%disp('	                  The method to write the dimensions ');
%disp('			                     rows * columns ');
%disp('');

end

